; This is a config file used by prepend_header tool to generate MP header for a given image.
;
; The following four sections are mandatory: BinID, Version, PartNumber and DataLength. Among
; which the DataLength key is not really needed to write in this file, as it would be calculated
; by the prepend_header tool and automatically filled in the MP header.

[MandatoryInfo]

BinID=ID_APP
Version=1.0.0.0
PartNumber=RTL8773

[OptionalInfo]

DependOnSocvConfig      =
DependOnOemConfig       =
DependOnFactoryMp       =
DependOnFsbl            =
DependOnOtaHeader       =
DependOnPatch           =
DependOnApp             =
DependOnAppData         =
DependOnAppDataTone     =
DependOnAppDataVp       =
DependOnAppDspParam     =
DependOnDspSys          =
DependOnDspPatch        =
DependOnDspScenario1    =
DependOnDspScenario2    =

Comment=
Author=
Date=
Revision=0x01