CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_REALTEK_SUBSYS_BLE_MGR=y
CONFIG_RTK_BT_BREDR=y
CONFIG_RTK_BR_PROFILE_A2DP=y
CONFIG_RTK_BR_PROFILE_AVRCP=y
CONFIG_RTK_BR_PROFILE_HFP=y
CONFIG_RTK_BR_PROFILE_PAN=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
#start display config
CONFIG_REALTEK_HONEYGUI=y
CONFIG_REALTEK_H264_DECODER=y
CONFIG_REALTEK_H264BSD=y
CONFIG_REALTEK_BUILD_EXAMPLE_VIDEO_WIDGET=y

CONFIG_DISPLAY=y
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_DISPLAY_ENABLE_LCDC=y
CONFIG_REALTEK_DISPLAY_ENABLE_PPE=y
CONFIG_REALTEK_DISPLAY_ENABLE_IDU=y
CONFIG_REALTEK_DISPLAY_GUI_ACC=y
CONFIG_REALTEK_DISPLAY_ENABLE_JPU=y

CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI=y
CONFIG_REALTEK_TOUCH_CHSC6417_ZEPHYR=y
CONFIG_REALTEK_KEY_BUTTON_8773G_ZEPHYR=y
CONFIG_GPIO=y
CONFIG_GPIO_ENABLE_DISABLE_INTERRUPT=y
CONFIG_I2C=y
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_NEWLIB_LIBC=y
#start display config
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_UART_ASYNC_API=y
CONFIG_SDHC=y
CONFIG_SDIO_STACK=y
CONFIG_HEAP_MEM_POOL_SIZE=2048
