#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

Import('SDK_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = []

CPPDEFINES = []
LINKFLAGS = []

path = ['../../app/designer/src/callbacks',
        '../../app/designer/src/ui',
        '../../app/designer/src/user' ]


src += ['../../app/designer/src/easy_demoEntry.c']

src += Glob('../../app/designer/src/callbacks/*.c')
src += Glob('../../app/designer/src/user/*.c')
src += Glob('../../app/designer/src/ui/*.c')


#SrcRemove(src,SDK_ROOT + '/src/mcu/driver/imdc/src/rtl_common/rtl_lcdc_dphy.c')


group = DefineGroup('ui', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES, LINKFLAGS = LINKFLAGS)


Return('group')
