#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

Import('SDK_ROOT')
#import config
from building import *

# add the general drivers.
src     = Glob('*.c')

cwd = GetCurrentDir()

CPPPATH = [cwd]
# SrcRemove(src,'example_gui_img.c')

group = DefineGroup('app', src, depend = [''], CPPPATH = CPPPATH)

Return('group')