/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

#ifndef MENU_CONFIG_H__
#define MENU_CONFIG_H__
// <<< Use Configuration Wizard in Context Menu >>>
///* Automatically generated file; DO NOT EDIT. */


// <h> Soc Device Config
#define CONFIG_REALTEK_8773E_DEVICE
#define CONFIG_REALTEK_LCD

// <q> LCD_C05300_390_450_QSPI
#define CONFIG_REALTEK_LCD_C05300_390_450_QSPI 0

// <q> LCD_SH8601Z_410_502_QSPI
#define CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI 0

// <q> LCD_ST7265_800480_RGB
#define CONFIG_REALTEK_LCD_ST7265_800480_RGB 1

// <q> NV3041A_480_272_QSPI
#define CONFIG_REALTEK_NV3041A_480_272_QSPI 0

// <q> SH8601A_454454_QSPI
#define CONFIG_REALTEK_SH8601A_454454_QSPI 0

// <q> ST7701S_480480_RGB
#define CONFIG_REALTEK_ST7701S_480480_RGB 0

// <q> TOUCH_CHSC6417
#define CONFIG_REALTEK_TOUCH_CHSC6417 0

// <q> TOUCH_GT911
#define CONFIG_REALTEK_TOUCH_GT911 0

// <q> TOUCH_LW
#define CONFIG_REALTEK_TOUCH_LW 0

// <q> KEY_BUTTON_8773E
#define CONFIG_REALTEK_KEY_BUTTON_8773E 1

// </h>

// <o> HoneyGUI Build Mode
//  <0=> Build Lib
//  <1=> Build Source Code
#define CONFIG_REALTEK_HONEYGUI_BUILD_MODE  1

#if CONFIG_REALTEK_HONEYGUI_BUILD_MODE == 0
#define CONFIG_REALTEK_HONEYGUI_LIB
#elif CONFIG_REALTEK_HONEYGUI_BUILD_MODE == 1
#define CONFIG_REALTEK_HONEYGUI_SRC
#define CONFIG_REALTEK_BUILD_HONEYGUI_SRC 1
#endif

#if (CONFIG_REALTEK_BUILD_HONEYGUI_SRC == 1)
// <o> HoneyGUI Demo Select
//  <0=> Base Widget Demo
//  <1=> SVG Widget Demo
//  <2=> GIF Widget Demo
//  <3=> Text Widget Demo
//  <4=> Gray Widget Demo
//  <5=> 3D Demo - Dog
//  <6=> 3D Demo - Earth
//  <7=> 3D Demo - Donut
//  <8=> 3D Demo - Pikachu GLTF
//  <9=> 3D Demo - Flag GLTF
//  <10=> 3D Demo - Robot GLTF
//  <11=> View Demo
//  <12=> List Demo
//  <13=> Menu Cellular Demo
//  <14=> Canvas Demo
//  <15=> Lite Arc Demo
//  <16=> Lite Rect Demo
//  <17=> Lite Circle Demo
//  <18=> QRCode Demo
//  <19=> Glass Effect Demo
//  <20=> Video Widget Demo
//  <21=> Paint Engine Demo
//  <22=> NanoVG Demo
//  <23=> Box2D Demo
//  <24=> Demo 410 502
//  <25=> Demo 466 466
//  <26=> TEST
//  <27=> AUTO TEST
//  <28=> Demo 240 240
//  <29=> Demo 800 480
//  <30=> HML Designer Demo
//  <31=> Particle Demo
//  <32=> Demo 280 456
//  <33=> Demo 320 384
//  <34=> Demo 320 385
#define CONFIG_REALTEK_HONEYGUI_DEMO_SELECT  0

#if CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 0
#define CONFIG_REALTEK_BUILD_EXAMPLE_IMAGE_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 1
#define CONFIG_REALTEK_BUILD_EXAMPLE_SVG_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 2
#define CONFIG_REALTEK_BUILD_EXAMPLE_GIF_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 3
#define CONFIG_REALTEK_BUILD_EXAMPLE_TEXT_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 4
#define CONFIG_REALTEK_BUILD_EXAMPLE_GRAY_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 5
#define CONFIG_REALTEK_BUILD_REAL_DOG_3D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 6
#define CONFIG_REALTEK_BUILD_REAL_EARTH_3D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 7
#define CONFIG_REALTEK_BUILD_REAL_DONUT_3D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 8
#define CONFIG_REALTEK_BUILD_REAL_PIKACHU_GLTF_3D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 9
#define CONFIG_REALTEK_BUILD_REAL_FLAG_GLTF_3D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 10
#define CONFIG_REALTEK_BUILD_REAL_ROBOT_GLTF_3D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 11
#define CONFIG_REALTEK_BUILD_REAL_VIEW
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 12
#define CONFIG_REALTEK_BUILD_EXAMPLE_LIST_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 13
#define CONFIG_REALTEK_BUILD_EXAMPLE_MENU_CELLULAR_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 14
#define CONFIG_REALTEK_BUILD_REAL_CANVAS
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 15
#define CONFIG_REALTEK_BUILD_REAL_LITE_ARC
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 16
#define CONFIG_REALTEK_BUILD_REAL_LITE_RECT
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 17
#define CONFIG_REALTEK_BUILD_REAL_LITE_CIRCLE
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 18
#define CONFIG_REALTEK_BUILD_EXAMPLE_QBCODE_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 19
#define CONFIG_REALTEK_BUILD_EXAMPLE_GLASS_EFFECT_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 20
#define CONFIG_REALTEK_BUILD_EXAMPLE_VIDEO_WIDGET
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 21
#define CONFIG_REALTEK_BUILD_REAL_PAINTENGINE
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 22
#define CONFIG_REALTEK_BUILD_REAL_NANOVG
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 23
#define CONFIG_REALTEK_BUILD_REAL_BOX2D
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 24
#define CONFIG_REALTEK_BUILD_GUI_410_502_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 25
#define CONFIG_REALTEK_BUILD_GUI_466_466_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 26
#define CONFIG_REALTEK_BUILD_TEST
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 27
#define CONFIG_REALTEK_BUILD_HONEYGUI_AUTO_TEST
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 28
#define CONFIG_REALTEK_BUILD_GUI_240_240_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 29
#define CONFIG_REALTEK_BUILD_GUI_800_480_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 30
#define CONFIG_REALTEK_BUILD_HML_DESIGNER
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 31
#define CONFIG_REALTEK_BUILD_PARTICLE_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 32
#define CONFIG_REALTEK_BUILD_GUI_280_456_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 33
#define CONFIG_REALTEK_BUILD_GUI_320_384_DEMO
#elif CONFIG_REALTEK_HONEYGUI_DEMO_SELECT == 34
#define CONFIG_REALTEK_BUILD_GUI_320_385_DEMO
#endif

#endif

// <h> HoneyGUI Config Function

// <c> Enable RTK GUI ROMFS
#define CONFIG_REALTEK_ROMFS
// </c>

#if (CONFIG_REALTEK_BUILD_HONEYGUI_SRC == 1)
#define CONFIG_REALTEK_HONEYGUI

// <c> Enable LetterShell
// #define CONFIG_REALTEK_BUILD_LETTER_SHELL
// </c>

// <c> Enable Monkey Test Log
// #define CONFIG_REALTEK_BUILD_MONKEY_TEST
// </c>

// <c> Enable h.264 decoder
//#define CONFIG_REALTEK_H264_DECODER 0
//#if (CONFIG_REALTEK_H264_DECODER == 1)
//#define CONFIG_REALTEK_H264BSD
//#endif
// </c>

// <c> Enable BOX2D
//#define CONFIG_REALTEK_BUILD_GUI_BOX2D
// </c>

// <c> Enable LITE3D
#define CONFIG_REALTEK_BUILD_LITE3D
// </c>

// <c> Enable XML Loader (HML)
// #define CONFIG_REALTEK_BUILD_XML_LOADER
// </c>

// <c> Enable Particle System
// #define CONFIG_REALTEK_BUILD_PARTICLE_SYSTEM
// </c>

// <c> Enable MiniMP3
// #define CONFIG_REALTEK_MINIMP3
// </c>

// <c> Enable Audio
// #define CONFIG_REALTEK_BUILD_AUDIO
// </c>

#endif
// </h>

// <<< end of configuration section >>>
#endif /* MENU_CONFIG_H__ */
