/*
 * Copyright (c) 2026 Realtek Semiconductor Corporation. All rights reserved.
 *
 * Classic Bluetooth (BR/EDR) SDP service records for bluetooth_ext (RTL8761B).
 */

#include "platform_autoconf.h"

#ifdef CONFIG_BT_EXT

#include <stdint.h>

#include "ameba_soc.h"
#include "bt_types.h"
#include "bt_sdp.h"

#include "bt_classic_sdp.h"
#include "bt_classic_spp.h"
#include "bt_classic_config.h"
#if BT_CLASSIC_ENABLE_HFP
#include "bt_classic_hfp.h"
#endif

static const char *const TAG = "BTEXT_CSDP";

#define RTK_COMPANY_ID  0x005D

/* DID/PnP record */
static const uint8_t did_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x4D,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PNP_INFORMATION >> 8),
	(uint8_t)(UUID_PNP_INFORMATION),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_BROWSE_GROUP_LIST >> 8),
	(uint8_t)SDP_ATTR_BROWSE_GROUP_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP >> 8),
	(uint8_t)UUID_PUBLIC_BROWSE_GROUP,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_LANG_BASE_ATTR_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_LANG_BASE_ATTR_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x09,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_LANG_ENGLISH >> 8),
	(uint8_t)SDP_LANG_ENGLISH,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_CHARACTER_UTF8 >> 8),
	(uint8_t)SDP_CHARACTER_UTF8,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_BASE_LANG_OFFSET >> 8),
	(uint8_t)SDP_BASE_LANG_OFFSET,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PNP_INFORMATION >> 8),
	(uint8_t)UUID_PNP_INFORMATION,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x03,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_DIP_SPECIFICATION_ID >> 8),
	(uint8_t)SDP_ATTR_DIP_SPECIFICATION_ID,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x03,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_DIP_VENDOR_ID >> 8),
	(uint8_t)SDP_ATTR_DIP_VENDOR_ID,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(RTK_COMPANY_ID >> 8),
	(uint8_t)RTK_COMPANY_ID,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_DIP_PRODUCT_ID >> 8),
	(uint8_t)SDP_ATTR_DIP_PRODUCT_ID,
	SDP_UNSIGNED_TWO_BYTE,
	0x22, 0x3B,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_DIP_PRODUCT_VERSION >> 8),
	(uint8_t)SDP_ATTR_DIP_PRODUCT_VERSION,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x00,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_DIP_PRIMARY_RECORD >> 8),
	(uint8_t)SDP_ATTR_DIP_PRIMARY_RECORD,
	SDP_BOOL_ONE_BYTE,
	true,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_DIP_VENDOR_ID_SOURCE >> 8),
	(uint8_t)SDP_ATTR_DIP_VENDOR_ID_SOURCE,
	SDP_UNSIGNED_TWO_BYTE,
	0x00, 0x01,
};

#if BT_CLASSIC_ENABLE_A2DP
/* A2DP Audio Sink record */
static const uint8_t a2dp_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x39,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AUDIO_SINK >> 8),
	(uint8_t)(UUID_AUDIO_SINK),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROTO_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROTO_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x10,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_L2CAP >> 8),
	(uint8_t)(UUID_L2CAP),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(PSM_AVDTP >> 8),
	(uint8_t)(PSM_AVDTP),
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AVDTP >> 8),
	(uint8_t)(UUID_AVDTP),
	SDP_UNSIGNED_TWO_BYTE,
	0x01,
	0x03,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_BROWSE_GROUP_LIST >> 8),
	(uint8_t)SDP_ATTR_BROWSE_GROUP_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP >> 8),
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_ADVANCED_AUDIO_DISTRIBUTION >> 8),
	(uint8_t)(UUID_ADVANCED_AUDIO_DISTRIBUTION),
	SDP_UNSIGNED_TWO_BYTE,
	0x01,
	0x03,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SUPPORTED_FEATURES >> 8),
	(uint8_t)SDP_ATTR_SUPPORTED_FEATURES,
	SDP_UNSIGNED_TWO_BYTE,
	0x00,
	0x03,
};
#endif /* BT_CLASSIC_ENABLE_A2DP */

#if BT_CLASSIC_ENABLE_AVRCP
/* AVRCP Controller (CT) record */
static const uint8_t avrcp_ct_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x3B,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AV_REMOTE_CONTROL >> 8),
	(uint8_t)(UUID_AV_REMOTE_CONTROL),
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AV_REMOTE_CONTROL_CONTROLLER >> 8),
	(uint8_t)(UUID_AV_REMOTE_CONTROL_CONTROLLER),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROTO_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROTO_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x10,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_L2CAP >> 8),
	(uint8_t)(UUID_L2CAP),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(PSM_AVCTP >> 8),
	(uint8_t)PSM_AVCTP,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AVCTP >> 8),
	(uint8_t)(UUID_AVCTP),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(0x0104 >> 8),
	(uint8_t)(0x0104),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AV_REMOTE_CONTROL >> 8),
	(uint8_t)(UUID_AV_REMOTE_CONTROL),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(0x0106 >> 8),
	(uint8_t)(0x0106),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)((SDP_ATTR_SUPPORTED_FEATURES) >> 8),
	(uint8_t)(SDP_ATTR_SUPPORTED_FEATURES),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(0x0001 >> 8),
	(uint8_t)(0x0001),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_BROWSE_GROUP_LIST >> 8),
	(uint8_t)SDP_ATTR_BROWSE_GROUP_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP >> 8),
	(uint8_t)UUID_PUBLIC_BROWSE_GROUP,
};

/* AVRCP Target (TG) record */
static const uint8_t avrcp_tg_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x38,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AV_REMOTE_CONTROL_TARGET >> 8),
	(uint8_t)(UUID_AV_REMOTE_CONTROL_TARGET),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROTO_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROTO_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x10,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_L2CAP >> 8),
	(uint8_t)(UUID_L2CAP),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(PSM_AVCTP >> 8),
	(uint8_t)PSM_AVCTP,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AVCTP >> 8),
	(uint8_t)(UUID_AVCTP),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(0x0104 >> 8),
	(uint8_t)(0x0104),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_AV_REMOTE_CONTROL >> 8),
	(uint8_t)(UUID_AV_REMOTE_CONTROL),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(0x0106 >> 8),
	(uint8_t)(0x0106),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)((SDP_ATTR_SUPPORTED_FEATURES) >> 8),
	(uint8_t)(SDP_ATTR_SUPPORTED_FEATURES),
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(0x0002 >> 8),
	(uint8_t)(0x0002),

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_BROWSE_GROUP_LIST >> 8),
	(uint8_t)SDP_ATTR_BROWSE_GROUP_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP >> 8),
	(uint8_t)UUID_PUBLIC_BROWSE_GROUP,
};
#endif /* BT_CLASSIC_ENABLE_AVRCP */

/* SPP SerialPort record. RFCOMM channel byte must match BT_CLASSIC_SPP_SERVER_CHANN registered in code. */
#if BT_CLASSIC_ENABLE_SPP
static const uint8_t spp_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x4C,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_SERIAL_PORT >> 8),
	(uint8_t)UUID_SERIAL_PORT,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROTO_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROTO_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x0c,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_L2CAP >> 8),
	(uint8_t)UUID_L2CAP,
	SDP_DATA_ELEM_SEQ_HDR,
	0x05,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_RFCOMM >> 8),
	(uint8_t)UUID_RFCOMM,
	SDP_UNSIGNED_ONE_BYTE,
	BT_CLASSIC_SPP_SERVER_CHANN,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_BROWSE_GROUP_LIST >> 8),
	(uint8_t)SDP_ATTR_BROWSE_GROUP_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP >> 8),
	(uint8_t)UUID_PUBLIC_BROWSE_GROUP,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_LANG_BASE_ATTR_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_LANG_BASE_ATTR_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x09,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_LANG_ENGLISH >> 8),
	(uint8_t)SDP_LANG_ENGLISH,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_CHARACTER_UTF8 >> 8),
	(uint8_t)SDP_CHARACTER_UTF8,
	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_BASE_LANG_OFFSET >> 8),
	(uint8_t)SDP_BASE_LANG_OFFSET,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_SERIAL_PORT >> 8),
	(uint8_t)UUID_SERIAL_PORT,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x02,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)((SDP_ATTR_SRV_NAME + SDP_BASE_LANG_OFFSET) >> 8),
	(uint8_t)(SDP_ATTR_SRV_NAME + SDP_BASE_LANG_OFFSET),
	SDP_STRING_HDR,
	0x0B,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x20, 0x70, 0x6f, 0x72, 0x74,
};
#endif /* BT_CLASSIC_ENABLE_SPP */

#if BT_CLASSIC_ENABLE_HFP
/* HFP HF record. RFCOMM channel byte must match BT_CLASSIC_HFP_HF_CHANN registered in code. */
static const uint8_t hfp_hf_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x37,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_HANDSFREE >> 8),
	(uint8_t)UUID_HANDSFREE,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_GENERIC_AUDIO >> 8),
	(uint8_t)UUID_GENERIC_AUDIO,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROTO_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROTO_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x0C,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_L2CAP >> 8),
	(uint8_t)UUID_L2CAP,
	SDP_DATA_ELEM_SEQ_HDR,
	0x05,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_RFCOMM >> 8),
	(uint8_t)UUID_RFCOMM,
	SDP_UNSIGNED_ONE_BYTE,
	BT_CLASSIC_HFP_HF_CHANN,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_BROWSE_GROUP_LIST >> 8),
	(uint8_t)SDP_ATTR_BROWSE_GROUP_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_PUBLIC_BROWSE_GROUP >> 8),
	(uint8_t)UUID_PUBLIC_BROWSE_GROUP,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_HANDSFREE >> 8),
	(uint8_t)UUID_HANDSFREE,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x06,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SUPPORTED_FEATURES >> 8),
	(uint8_t)SDP_ATTR_SUPPORTED_FEATURES,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x3F,
};

/* HFP AG record. RFCOMM channel byte must match BT_CLASSIC_HFP_AG_CHANN registered in code. */
static const uint8_t hfp_ag_sdp_record[] = {
	SDP_DATA_ELEM_SEQ_HDR,
	0x34,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SRV_CLASS_ID_LIST >> 8),
	(uint8_t)SDP_ATTR_SRV_CLASS_ID_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_HANDSFREE_AUDIO_GATEWAY >> 8),
	(uint8_t)UUID_HANDSFREE_AUDIO_GATEWAY,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_GENERIC_AUDIO >> 8),
	(uint8_t)UUID_GENERIC_AUDIO,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROTO_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROTO_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x0C,
	SDP_DATA_ELEM_SEQ_HDR,
	0x03,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_L2CAP >> 8),
	(uint8_t)UUID_L2CAP,
	SDP_DATA_ELEM_SEQ_HDR,
	0x05,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_RFCOMM >> 8),
	(uint8_t)UUID_RFCOMM,
	SDP_UNSIGNED_ONE_BYTE,
	BT_CLASSIC_HFP_AG_CHANN,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_PROFILE_DESC_LIST >> 8),
	(uint8_t)SDP_ATTR_PROFILE_DESC_LIST,
	SDP_DATA_ELEM_SEQ_HDR,
	0x08,
	SDP_DATA_ELEM_SEQ_HDR,
	0x06,
	SDP_UUID16_HDR,
	(uint8_t)(UUID_HANDSFREE_AUDIO_GATEWAY >> 8),
	(uint8_t)UUID_HANDSFREE_AUDIO_GATEWAY,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x06,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_EXT_NETWORK >> 8),
	(uint8_t)SDP_ATTR_EXT_NETWORK,
	SDP_UNSIGNED_ONE_BYTE,
	0x01,

	SDP_UNSIGNED_TWO_BYTE,
	(uint8_t)(SDP_ATTR_SUPPORTED_FEATURES >> 8),
	(uint8_t)SDP_ATTR_SUPPORTED_FEATURES,
	SDP_UNSIGNED_TWO_BYTE,
	0x01, 0x2F,
};
#endif /* BT_CLASSIC_ENABLE_HFP */

void bt_classic_sdp_init(void)
{
	bt_sdp_record_add((void *)did_sdp_record);
#if BT_CLASSIC_ENABLE_A2DP
	bt_sdp_record_add((void *)a2dp_sdp_record);
#endif
#if BT_CLASSIC_ENABLE_AVRCP
	bt_sdp_record_add((void *)avrcp_ct_sdp_record);
	bt_sdp_record_add((void *)avrcp_tg_sdp_record);
#endif
#if BT_CLASSIC_ENABLE_SPP
	bt_sdp_record_add((void *)spp_sdp_record);
#endif
#if BT_CLASSIC_ENABLE_HFP
	bt_sdp_record_add((void *)hfp_hf_sdp_record);
	bt_sdp_record_add((void *)hfp_ag_sdp_record);
#endif
	/* HID SDP record is registered inside bt_classic_hid_init(). */
	RTK_LOGS(TAG, RTK_LOG_INFO,
		"SDP records added: DID (A2DP=%d AVRCP=%d SPP=%d HFP=%d)\r\n",
		BT_CLASSIC_ENABLE_A2DP, BT_CLASSIC_ENABLE_AVRCP,
		BT_CLASSIC_ENABLE_SPP, BT_CLASSIC_ENABLE_HFP);
}

#endif /* CONFIG_BT_EXT */
