#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")
CPPDEFINES = []

if GetDepend('CONFIG_REALTEK_BUILD_LVGL_GUI'):
    src = Glob('*.c')
    
    CPPDEFINES += ['LV_KCONFIG_IGNORE']
    CPPDEFINES += ['LV_LVGL_H_INCLUDE_SIMPLE']
    CPPDEFINES += ['LV_USE_DEMO_BENCHMARK']
    CPPDEFINES += ['LV_USE_DEMO_WIDGETS']
    CPPDEFINES += ['LV_CONF_INCLUDE_SIMPLE']

CPPPATH = [cwd]


group = DefineGroup('port_lvgl', src, depend = ['CONFIG_REALTEK_BUILD_HONEYGUI_SRC'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

group = DefineGroup('port_lvgl', src, depend = ['CONFIG_REALTEK_BUILD_HONEYGUI_LIB'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
