#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

Import('SDK_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Glob('*.c')

CPPDEFINES = ['TARGET_RTL8773E']
CPPDEFINES += ['SUPPORT_ACCESS_SHM = 1']
# CPPDEFINES += ['PRE_UPPERSTACK=1']
# CPPDEFINES += ['ENABLE_HONEYGUI']

path = [SDK_ROOT + '/inc/app',
        SDK_ROOT + '/inc/os',
        SDK_ROOT + '/inc/platform',
        SDK_ROOT + '/inc/rtl87x3ep/platform',
        SDK_ROOT + '/inc/rtl87x3ep/hal',
        SDK_ROOT + '/inc/ble_mgr',
        SDK_ROOT + '/inc/framework/bt',
        SDK_ROOT + '/inc/framework/remote',
        SDK_ROOT + '/inc/framework/sysm',
        SDK_ROOT + '/inc/framework/audio',
        SDK_ROOT + '/inc/bluetooth/gap',
        SDK_ROOT + '/inc/bluetooth/profile',
        SDK_ROOT + '/inc/rtl87x3ep/hal/stack',
        SDK_ROOT + '/bin/rtl87x3ep/upperstack_stamp',
        SDK_ROOT + '/bin/rtl87x3ep/flash_map_config/16M/flash_16M',
        SDK_ROOT + '/inc/hal/platform',
        SDK_ROOT + '/inc/hal/io',
        SDK_ROOT + '/inc/rtl87x3ep/io',
        SDK_ROOT + '/inc/os/FreeRTOS']


LINKFLAGS = '--diag_suppress=L6314 --datacompressor off'
bsp = DefineGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES, LINKFLAGS = LINKFLAGS)

lib_src = []
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/gap_lib/gap_utils_4M.lib']
# lib_src += [SDK_ROOT + '/bin/rtl87x3ep/framework/console.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/framework/remote.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/framework/sysm.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/ble_mgr/ble_mgr_all.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/framework/btm.lib']
# lib_src += [SDK_ROOT + '/bin/rtl87x3ep/filesystem.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/ROM.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/upperstack_4M.lib']
lib_src += [SDK_ROOT + '/bin/rtl87x3ep/hal_utils.lib']

LIBDEFINES = ['TARGET_RTL8773E']
lib = DefineGroup('lib', lib_src, depend = [''], CPPPATH = path, CPPDEFINES = LIBDEFINES, LINKFLAGS = LINKFLAGS)


io_hal_src = []
io_hal_src += [SDK_ROOT + '/src/mcu/io_hal/common/hw_tim.c']
path = [SDK_ROOT + '/inc/hal/io']
IO_HAL_CPPDEFINES = []
io_hal = DefineGroup('io_hal', io_hal_src, depend = [''], CPPPATH = path, CPPDEFINES = IO_HAL_CPPDEFINES)

rtc_calendar_src = []
rtc_calendar_src += [SDK_ROOT + '/src/mcu/module/rtc_calendar/rtc_calendar.c']
path = [SDK_ROOT + '/src/mcu/module/rtc_calendar']
rtc_calendar = DefineGroup('rtc_calendar', rtc_calendar_src, depend = [''], CPPPATH = path)

objs = bsp + lib + io_hal + rtc_calendar
Return('objs')
