#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

objs = DefineGroup('hmi_ble', src, depend=[''], CPPPATH=CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
