
#ifndef GUI_VERSION_H
#define GUI_VERSION_H

#define VERSION_TAG "v2.1.1.0"
#define VERSION_BRANCH "HEAD"
#define VERSION_COMMIT "23c0bb448"
#define VERSION_BUILD_DATE "2026-05-07 16:47:46"
#define VERSION_REPO_STATUS "clean"

#endif // GUI_VERSION_H
