#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

import os
from building import *

cwd  = GetCurrentDir()

# Core sources at this level + the default RAM port.
src = [
    'file_db.c',
    'file_db_dir.c',
    'file_db_alloc.c',
    'file_db_crc.c',
    'file_db_log.c',
    os.path.join('port', 'ram', 'file_db_port_ram.c'),
]

CPPPATH = [cwd]

group = DefineGroup('file_db', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
