#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

Import('SDK_ROOT')
Import('HONEYGUI_ROOT')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
group = []

if GetDepend(['CONFIG_REALTEK_HONEYGUI_LIB']):
    # Precompiled libgui.a: designer project provides the app UI.
    src = Glob('*.c')
    group = DefineGroup('app', src, depend=[''], CPPPATH=CPPPATH)
    group += SConscript('designer/src/SConscript')
elif GetDepend(['CONFIG_REALTEK_HONEYGUI_SRC']):
    # Designer UI and HoneyGUI example demos both export app_init; build only one.
    src = Glob('*.c')
    group = DefineGroup('app', src, depend=[''], CPPPATH=CPPPATH)
    if GetDepend(['CONFIG_REALTEK_BUILD_DASHBOARD_DESIGNER']):
        group += SConscript('designer/src/SConscript')
    else:
        group += SConscript(HONEYGUI_ROOT + '/example/SConscript')

Return('group')