#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

Import('SDK_ROOT')
Import('HONEYGUI_ROOT')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
group = []

if GetDepend(['CONFIG_REALTEK_HONEYGUI_LIB']):
    # Use local application code, exclude example_gui_img.c
    src = Glob('*.c')
    group = DefineGroup('app', src, depend=[''], CPPPATH=CPPPATH)
elif GetDepend(['CONFIG_REALTEK_HONEYGUI_SRC']):
    # Use source code from submodule (example), exclude local example_gui_img.c
    src = Glob('*.c')
    SrcRemove(src, 'example_gui_img.c')
    group = DefineGroup('app', src, depend=[''], CPPPATH=CPPPATH)
    group += SConscript(HONEYGUI_ROOT + '/example/SConscript')

Return('group')